/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2015
 *
 * Name: Ryan Greene, Jack Napor, Danny Toback, & Richard Huffman
 * Date: Nov 13, 2015
 * Time: 8:00:51 AM
 *
 * Project: csci205FinalProject
 * Package: Game
 * File: ZombieView
 * Description: The view for the whole game, works with the ZombieModel and ZombieController
 *
 * ****************************************
 */
package Game;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rtg008
 */
public class ZombieView extends javax.swing.JFrame {

    /**
     * Creates new form ZombieView
     */
    public ZombieView() {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/background.jpg"))));
        JLabel logo = new JLabel(new ImageIcon(getClass().getResource("/rsz_logo1.png")));
        logo.setBounds(10, 10, 300, 144);
        logo.setBorder(BorderFactory.createLineBorder(Color.black, 5));
        
        this.getContentPane().add(logo);
        

        initComponents();
        getjLabel1().setVisible(false);
        getjLabel2().setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Board = new javax.swing.JPanel();
        controls = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        vitalsLabel = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();
        ammo = new javax.swing.JLabel();
        damage = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zombie Survival");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 660));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Board.setBackground(java.awt.Color.lightGray);
        Board.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Board.setMinimumSize(new java.awt.Dimension(900, 650));
        Board.setPreferredSize(new java.awt.Dimension(900, 650));
        Board.setLayout(new java.awt.BorderLayout());

        controls.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        controls.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        controls.setText("<html> <h1 style=\"text-align: center; text-decoration: underline;\"> CONTROLS<br></h1><p style=\"text-align: center;\"> <ul><li> Use arrow keys to move.</li> <br><li> Press Spacebar to shoot.</li> <br> <li> Avoid holes- you can fall in and die, and zombies spawn from them.</li> <br> <li> Pick up powerups around the map. </li> </ul> <br> <br><h2 style=\"text-align: center; font-size:30px;\">Survive.</h2></p> </html>");
        controls.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        controls.setMinimumSize(new java.awt.Dimension(900, 650));
        controls.setPreferredSize(new java.awt.Dimension(900, 650));
        controls.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Board.add(controls, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 500, 500));

        btnStart.setText("Start");
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnExit.setText("Exit");
        btnExit.setName(""); // NOI18N
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        vitalsLabel.setAutoscrolls(true);
        getContentPane().add(vitalsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, 240));

        lblRound.setFont(new java.awt.Font("Gentium Book Basic", 1, 50)); // NOI18N
        lblRound.setForeground(java.awt.Color.white);
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 500, 40));

        ammo.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        ammo.setForeground(new java.awt.Color(255, 255, 255));
        ammo.setText("UNLIMITED AMMO!");
        getContentPane().add(ammo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 400, 40));

        damage.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        damage.setForeground(new java.awt.Color(255, 255, 255));
        damage.setText("DAMAGE INCREASED!");
        getContentPane().add(damage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 400, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZombieView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZombieView().setVisible(true);
            }
        });
    }

    public JPanel getBoard() {
        return Board;
    }

    public JButton getBtnStart() {
        return btnStart;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JLabel getVitals() {
        return vitalsLabel;
    }

    public JLabel getLblRound() {
        return lblRound;
    }
    
    public JLabel getjLabel1(){
        return damage;
    }
    
    public JLabel getjLabel2(){
        return ammo;
    }
    public JLabel getcontrols(){
        return controls;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Board;
    private javax.swing.JLabel ammo;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel controls;
    private javax.swing.JLabel damage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel vitalsLabel;
    // End of variables declaration//GEN-END:variables
}
